[package]
name = "palscii"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
fontdue = "0.6.2"
image = "0.23.14"

[dev-dependencies]
test-case = "1.2.0"